version: 1.0.0
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.5.1

jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release
      
  build:
    docker:
      - image: circleci/node:11.4.0

    steps:
      - checkout
      - run: npm install
      - run: npm run e2e:headless