version: 1.0.0
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.5.1

jobs:
  build:
    docker:
      - image: circleci/node:11.4.0

    steps:
      - checkout
      - run: npm install
      - run: npm install cypress 
      - run: npm run e2e:headless