version: 2
jobs:
  build:
    docker:
      -image: circleci/node:11.4.0
    steps:
      - checkout # check out the code in the project directory
      - run: node install
      - run: npm run e2e:headless